Ext.define('App.view.person.ShowDetails', {
    extend: 'Ext.Panel',
    xtype: 'personshowdetails',

    cls: 'person-details',
    title: '詳細情報',

    bind: {
        record: '{record}'
    },

    tpl: [
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">氏名</div>',
                '<div class="value">{username}</div>',
            '</div>',
            '<tpl if="phone">',
                '<div class="item">',
                    '<div class="label">電話番号</div>',
                    '<div class="value">{phone}</div>',
                '</div>',
            '</tpl>',
            '<tpl if="extension">',
                '<div class="item">',
                    '<div class="label">内線</div>',
                    '<div class="value">{extension}</div>',
                '</div>',
            '</tpl>',
        '</div>',
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">メールアドレス</div>',
                '<div class="value">{email}</div>',
            '</div>',
            '<tpl if="skype">',
                '<div class="item">',
                    '<div class="label">Skype</div>',
                    '<div class="value">{skype}</div>',
                '</div>',
            '</tpl>',
            '<tpl if="linkedin">',
                '<div class="item">',
                    '<div class="label">LinkedIn</div>',
                    '<div class="value">{linkedin}</div>',
                '</div>',
            '</tpl>',
        '</div>',
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">誕生日</div>',
                '<div class="value">{birthday:date("Y年n月j日")}</div>',
                '<div class="extra">{birthday:dateDiff(new Date())}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">入社日</div>',
                '<div class="value">{started:date("Y年n月j日")}</div>',
                '<tpl if="!ended">',
                    '<div class="extra">{started:dateDiff(new Date())}</div>',
                '</tpl>',
            '</div>',
            '<tpl if="ended">',
                '<div class="item">',
                    '<div class="label">退職日</div>',
                    '<div class="value">{ended:date("Y年n月j日")}</div>',
                    '<div class="extra">{started:dateDiff(values.ended)}</div>',
                '</div>',
            '</tpl>',
        '</div>'
    ]
});
